"""
Django settings for oauau project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'l0o2cer+vv8ufj5%swi2qumos7xhr&)1)!e!*qk1d=+vg_h*-j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'oauau.newsletter',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'oauau.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'oauau.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True



SITE_ID = 1

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
    os.path.join(BASE_DIR, "media"),
)

MAILCHIMP_API_KEY = ''
MAILCHIMP_WORKBOOK_LIST_ID = 'b595af5d99'
MAILCHIMP_WORKBOOK_LIST_NAME = 'O Au Au - Livro de atividades 1'

MAILCHIMP_LAUNCH_LIST_ID = 'a7fdd160e3'
MAILCHIMP_LAUNCH_LIST_NAME = 'O Au Au - Lançamento'

MAILCHIMP_PROMOTION_5_DAYS_LIST_ID = 'bde4e35640'
MAILCHIMP_PROMOTION_5_DAYS_LIST_NAME = 'O au au - Promoção 5 dias'


MADMIMI_USER = ''
MADMIMI_API_KEY = ''
MADMIMI_NEWSLETTER_LIST_ID = 'O Au Au'
MADMIMI_NEWSLETTER_LIST_NAME = 'O Au Au'

MADMIMI = 'madmimi'
MAILCHIMP = 'mailchimp'

CURRENT_EMAIL_MARKETING_PROVIDER = MAILCHIMP

EMAIL_HOST = ""
EMAIL_HOST_PASSWORD = ""
EMAIL_HOST_USER = ""
DEFAULT_FROM_EMAIL = "(O au au) " \
                     "<noreply@oauau.com.br>"

try:
    from .developmentsettings import *
except ImportError:
    from .productionsettings import *
